### ISSUE TITLE
Look amazing, are you support for multi-touch on Wacom?

### ISSUE THREAD

**Issue by natsupy** [hecomi/uWintab#1]
I don't test it, not yet, but it'll great if support multi-touch on Wacom xD

**Comment by zalo** [comment]
This particular plugin does not support multitouch (Wintab and WacomMT are two different libraries/.dlls), but I found it's possible to take [the old WacomMT sample code ](https://developer-docs.wacom.com/display/DevDocs/Feel+Multi-touch+Sample+Code+Downloads), retarget it for .NET 3.5 (replacing instances of IntPtr.Add() with conversions to int64, additions, and conversions back to IntPtrs), and adapt the .NET WinForms example code to a basic Unity component (that manages subscription, receipt of, and processing of Multitouch events).

If you build the WacomMTDN.dll yourself, then you can use [my multitouch integration here](https://gist.github.com/zalo/a88b6c188cbe504784374de656afe3c4).

Here's a video of it working with uWintab:
https://drive.google.com/file/d/1Kos14z3qF9KtPldrkvs3dCnm-EL164iy/view?usp=sharing

**Comment by natsupy** [comment]
Yay thank you, I will try them!

**Comment by hecomi** [comment]
Sorry for my late reply... X(

As @zalo said, the multitouch function is the funtion of the different library. So uWintab itself will never support it, sorry.

@zalo > Thank you for the great information, I'll also check your code for my study!
