### ISSUE TITLE
Support for Microsoft Surface and Pen

### ISSUE THREAD

**Issue by LisaLichtenberger** [hecomi/uWintab#2]
Hello!

I would like to use this API to receive pen input in my Unity project which will be build as a Windows Standalone in the end.
Is it possible to use this API on a Microsoft Surface with the pen? 
I already tried to run the example scene, but unfortunately it seems that it doesn´t recognize the tablet and my pen. The state shown in the game view says "Not Connected", name and version are also empty. 
Do I have to make any further settings?

Best regards :)

**Comment by hecomi** [comment]
Sorry for my late reply..., and uWintab doesn't support Surface's pen API because it is completely different from Wintab API.
